services:
  db-mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    expose:
      - 27017

  be-nest:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - NODE_ENV=production
      - MONGODB_URI=mongodb://root:123456@db-mongo:27017/nestjs?authSource=admin
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - db-mongo
volumes:
  mongodb:
